[book]
authors = ["Kabu Contributors"]
language = "en"
multilingual = false
src = "book"
title = "Kabu documentation"

[build]
build-dir = "target/book"

[preprocessor]
[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]
[output.html]
additional-js = ["book/js/mermaid.min.js", "book/js/mermaid-init.js"]
