[package]
name = "nodebench"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
kabu-core-actors.workspace = true
kabu-core-blockchain.workspace = true
kabu-core-blockchain-actors.workspace = true
kabu-evm-db.workspace = true
kabu-execution-multicaller.workspace = true
kabu-node-actor-config.workspace = true
kabu-types-blockchain.workspace = true
kabu-types-events.workspace = true

alloy.workspace = true
chrono.workspace = true
clap.workspace = true
env_logger.workspace = true
eyre.workspace = true
futures.workspace = true
tokio.workspace = true
