[package]
name = "kabu-rpc-handler"
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
kabu-core-blockchain.workspace = true
kabu-core-components = { workspace = true }
kabu-evm-db.workspace = true
kabu-evm-utils.workspace = true
kabu-rpc-state.workspace = true
kabu-storage-db.workspace = true
kabu-types-blockchain.workspace = true
kabu-types-market.workspace = true

hex.workspace = true
serde.workspace = true
serde_json.workspace = true

alloy-primitives.workspace = true
revm.workspace = true

# async
tokio.workspace = true
tokio-util.workspace = true

# tracing + error handling
eyre.workspace = true
tracing.workspace = true

# reth
reth-tasks.workspace = true

# web
axum.workspace = true
tower-http.workspace = true
utoipa.workspace = true
