[package]
name = "kabu-strategy-backrun"
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
kabu-core-blockchain.workspace = true
kabu-core-components = { workspace = true }
kabu-defi-abi.workspace = true
kabu-defi-address-book.workspace = true
kabu-defi-pools.workspace = true
kabu-evm-db.workspace = true
kabu-node-debug-provider.workspace = true
kabu-types-blockchain.workspace = true
kabu-types-entities.workspace = true
kabu-types-events.workspace = true
kabu-types-market.workspace = true
kabu-types-swap.workspace = true

chrono.workspace = true
eyre.workspace = true
influxdb.workspace = true
lazy_static.workspace = true
num_cpus.workspace = true
rayon.workspace = true
reth-tasks.workspace = true
revm.workspace = true
serde.workspace = true
tokio.workspace = true
tracing.workspace = true

# alloy
alloy-eips.workspace = true
alloy-evm.workspace = true
alloy-network.workspace = true
alloy-primitives.workspace = true
alloy-provider.workspace = true
alloy-rpc-types.workspace = true
alloy-rpc-types-trace.workspace = true
alloy-sol-types.workspace = true

[[bench]]
harness = false
name = "swap_calculation_bench"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["async_tokio"] }
